#pragma once

//////////////// OBJECT PLAYER MAP ////////////////
#define OBJECT_TYPE_MARIO			0
#define OBJECT_TYPE_BRICK			1
#define OBJECT_TYPE_GOOMBA			2
#define OBJECT_TYPE_TAIL			3
#define OBJECT_TYPE_COIN			4
#define OBJECT_TYPE_PLATFORM		5
#define OBJECT_TYPE_QUESTIONBRICK	6
#define OBJECT_TYPE_MUSHROOM		7
#define OBJECT_TYPE_LEAF			8
#define OBJECT_TYPE_POINT			9
#define OBJECT_TYPE_KOOPA			10
#define OBJECT_TYPE_VFTRAP			11
#define OBJECT_TYPE_PIPELINE		12
#define OBJECT_TYPE_FIREBALLS		13
#define OBJECT_TYPE_FIREBALL_OF_MARIO 14
#define OBJECT_TYPE_FLOWER_BOX		21
#define OBJECT_TYPE_AUTOMATION	22
#define OBJECT_TYPE_PORTAL	50

//////////////// OBJECT WORLD MAP ////////////////
#define OBJECT_TYPE_MARIO_WORLD		15
#define OBJECT_TYPE_GRASS_WORLD		16
#define OBJECT_TYPE_GOSH_BOX_WORLD	17
#define OBJECT_TYPE_KOOPA_WORLD		18
#define OBJECT_TYPE_HELP_WORLD		19
#define OBJECT_TYPE_DOOR_WORLD		20